import{A as S,S as g,N as h,K as b}from"./assets/vendor-26107bcc.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();document.addEventListener("DOMContentLoaded",()=>{y(".accordion-container"),y(".accordion-container-about")});function y(e){document.querySelectorAll(`${e} .ac`).forEach(o=>k(o)),new S(e,{duration:400,showMultiple:!0,onOpen:o=>{f(o),w(o,!0)},onClose:o=>{f(o),w(o,!1)}})}function k(e){const t=e.querySelector(".arrow-down"),o=e.querySelector(".arrow-up");t.style.display="block",o.style.display="none"}function f(e){const t=e.querySelector(".arrow-down"),o=e.querySelector(".arrow-up");t.style.display=t.style.display==="none"?"block":"none",o.style.display=o.style.display==="none"?"block":"none"}function w(e,t){e.querySelector(".ac-trigger").setAttribute("aria-expanded",t)}const E=document.querySelector(".hero__email-link");E.textContent=window.innerWidth<375?"email":"lloydjefferson@gmail.com";const m=document.querySelector(".header__backdrop"),q=document.querySelector(".header__menu-btn"),x=document.querySelector(".header__menu-close-btn");q.addEventListener("click",()=>{window.innerWidth<768?m.classList.remove("visually-hidden"):m.classList.toggle("visually-hidden")});x.addEventListener("click",()=>{m.classList.add("visually-hidden")});new g(".swiper-container",{modules:[h,b],spaceBetween:16,grabCursor:!0,keyboard:{enabled:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},breakpoints:{375:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:4}}});new g(".projectsSwiper",{modules:[h,b],slidesPerView:"auto",loop:!0,keyboard:{enabled:!0},spaceBetween:500,grabCursor:!0,navigation:{nextEl:".swiper-button-next1",prevEl:".swiper-button-prev1"}});async function _(){try{const e=await fetch("https://portfolio-js.b.goit.study/api/reviews");if(!e.ok)throw new Error(e.statusText||e.status);const t=await e.json();t.error?v(t.error):j(t)}catch{v("Failed to fetch reviews. Please try again later.")}}function j(e){const t=document.getElementById("reviewsList");if(t.innerHTML="",e.length===0)t.innerHTML='<div class="swiper-slide">Not found</div>';else{const o=e.map(i=>`
            <li class="swiper-slide">
                <div class="review-card" id="review_${i._id}"> 
                    <div class="avatar-review-js">
                        <img class="review-img-js" src="${i.avatar_url}" alt="Avatar of ${i.author}">
                    </div>
                    <div class="review-content-js">
                        <p class="author-review-js">${i.author}</p>
                        <p class="text-review-js">${i.review}</p>
                    </div>
               </div>
                </li>`).join("");t.innerHTML=o}}function v(e){alert(e)}document.addEventListener("DOMContentLoaded",_);const a=document.querySelector(".form-sect-work"),L=document.querySelector(".backdrop-sect-work"),n=a.elements.email_work,l=a.elements.message_work,I=document.querySelector(".btn-close-work"),d=document.querySelector(".input-email-text"),u=document.querySelector(".input-email-text2"),p="key",O="https://65ef278dead08fa78a4fefb5.mockapi.io/contacts/portfolio-js";function A(){const e=JSON.parse(localStorage.getItem(p));e&&(n.value=e.email,l.value=e.comments)}A();a.addEventListener("submit",P);a.addEventListener("input",()=>{const e={email:n.value.trim(),comments:l.value.trim()};localStorage.setItem(p,JSON.stringify(e)),n.value.includes("@")?(n.classList.add("input-email-green"),d.style.display="block",u.style.display="none"):n.value.includes("@")||(n.classList.add("input-email-red"),n.classList.remove("input-email-green"),d.style.display="none",u.style.display="block",n.value===""&&(n.classList.remove("input-email-green"),n.classList.remove("input-email-red"),d.style.display="none",u.style.display="none"))});async function P(e){try{if(e.preventDefault(),n.value===""||l==="")return alert("All form fields must be filled in");const t={email:n.value.trim(),comments:l.value.trim()};await M({email:t.email,comment:t.comments}),L.classList.add("is-open"),localStorage.removeItem(p),a.reset()}catch(t){console.log(t)}}I.addEventListener("click",()=>{L.classList.remove("is-open")});function M(e){try{return fetch(O,{method:"POST",body:JSON.stringify(e),headers:{"Content-Type":"application/json"}}).then(t=>{if(!t.ok)throw new Error(t.status||t.statusText);return t.json()})}catch(t){console.log(t),alert("Error! Please enter the data again")}}
//# sourceMappingURL=commonHelpers.js.map
