import{A,S as p,N as f,K as y,M as q}from"./assets/vendor-2e5c0932.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();document.addEventListener("DOMContentLoaded",()=>{h(".accordion-container"),h(".accordion-container-about")});function h(e){document.querySelectorAll(`${e} .ac`).forEach(o=>x(o)),new A(e,{duration:400,showMultiple:!0,onOpen:o=>{b(o),L(o,!0)},onClose:o=>{b(o),L(o,!1)}})}function x(e){const t=e.querySelector(".arrow-down"),o=e.querySelector(".arrow-up");t.style.display="block",o.style.display="none"}function b(e){const t=e.querySelector(".arrow-down"),o=e.querySelector(".arrow-up");t.style.display=t.style.display==="none"?"block":"none",o.style.display=o.style.display==="none"?"block":"none"}function L(e,t){e.querySelector(".ac-trigger").setAttribute("aria-expanded",t)}const I=document.querySelector(".hero__email-link");I.textContent=window.innerWidth<375?"email":"lloydjefferson@gmail.com";const m=document.querySelector(".header__backdrop"),O=document.querySelector(".header__menu-btn"),P=document.querySelector(".header__menu-close-btn");O.addEventListener("click",()=>{window.innerWidth<768?m.classList.remove("visually-hidden"):m.classList.toggle("visually-hidden")});P.addEventListener("click",()=>{m.classList.add("visually-hidden")});new p(".swiper-container",{modules:[f,y],slidesPerView:4,allowTouchMove:!0,slideToClickedSlide:!0,spaceBetween:16,grabCursor:!0,keyboard:{enabled:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},breakpoints:{375:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:4}}});new p(".projectsSwiper",{modules:[f,y],slidesPerView:"auto",loop:!0,keyboard:{enabled:!0},spaceBetween:500,grabCursor:!0,navigation:{nextEl:".swiper-button-next1",prevEl:".swiper-button-prev1"}});async function _(){try{const e=await fetch("https://portfolio-js.b.goit.study/api/reviews");if(!e.ok)throw new Error(e.statusText||e.status);const t=await e.json();t.error?S(t.error):j(t)}catch{S("Failed to fetch reviews. Please try again later.")}}function j(e){const t=document.getElementById("reviewsList");if(t.innerHTML="",e.length===0)t.innerHTML='<div class="swiper-slide">Not found</div>';else{const o=e.map(i=>`
            <li class="swiper-slide" id="swiper-slide">
                <div class="review-card" id="review_${i._id}"> 
                    <div class="avatar-review-js">
                        <img class="review-img-js" src="${i.avatar_url}" alt="Avatar of ${i.author}">
                    </div>
                    <div class="review-content-js">
                        <p class="author-review-js">${i.author}</p>
                        <p class="text-review-js">${i.review}</p>
                    </div>
               </div>
                </li>`).join("");t.innerHTML=o}}function S(e){alert(e)}document.addEventListener("DOMContentLoaded",_);document.addEventListener("DOMContentLoaded",function(){function t(n,l){n.forEach(function(v){const k=v.target.querySelectorAll(".my-covers-item-img");v.isIntersecting&&k.forEach(function(g){g.style.animation="none",requestAnimationFrame(function(){setTimeout(o,50,g)})})})}function o(n){n.style.animation="slideInFromBottomRight 2s ease-in-out forwards"}const i={root:null,threshold:.1},r=new IntersectionObserver(t,i);document.querySelectorAll(".covers-item").forEach(function(n){r.observe(n)})});const a=document.querySelector(".form-sect-work"),E=document.querySelector(".backdrop-sect-work"),s=a.elements.email_work,d=a.elements.message_work,M=document.querySelector(".btn-close-work"),c=document.querySelector(".input-email-text"),u=document.querySelector(".input-email-text2"),w="key",T="https://65ef278dead08fa78a4fefb5.mockapi.io/contacts/portfolio-js";function C(){const e=JSON.parse(localStorage.getItem(w));e&&(s.value=e.email,d.value=e.comments)}C();a.addEventListener("submit",V);a.addEventListener("input",()=>{const e={email:s.value.trim(),comments:d.value.trim()};localStorage.setItem(w,JSON.stringify(e)),s.value.includes("@")?(s.classList.add("input-email-green"),c.style.display="block",u.style.display="none"):s.value.includes("@")||(s.classList.add("input-email-red"),s.classList.remove("input-email-green"),c.style.display="none",u.style.display="block",s.value===""&&(s.classList.remove("input-email-green"),s.classList.remove("input-email-red"),c.style.display="none",u.style.display="none"))});async function V(e){try{if(e.preventDefault(),s.value===""||d==="")return alert("All form fields must be filled in");const t={email:s.value.trim(),comments:d.value.trim()};await B({email:t.email,comment:t.comments}),s.classList.remove("input-email-green"),s.classList.remove("input-email-red"),c.style.display="none",u.style.display="none",E.classList.add("is-open"),localStorage.removeItem(w),a.reset()}catch(t){console.log(t)}}M.addEventListener("click",()=>{E.classList.remove("is-open")});function B(e){try{return fetch(T,{method:"POST",body:JSON.stringify(e),headers:{"Content-Type":"application/json"}}).then(t=>{if(!t.ok)throw new Error(t.status||t.statusText);return t.json()})}catch(t){console.log(t),alert("Error! Please enter the data again")}}new p(".about-swiper-container",{mousewheel:{invert:!0},loop:!0,setWrapperSize:!0,modules:[f,y,q],spaceBetween:0,simulateTouch:!0,grabCursor:!0,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},breakpoints:{375:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:6}}});
//# sourceMappingURL=commonHelpers.js.map
